In [3]:
import pandas as pd
import numpy as np

In [4]:
data=['beijing','shanghai','tianjin','lanzhou']
indexs=['a','b','c','d']
pd.Series(data=data,index=indexs)

a     beijing
b    shanghai
c     tianjin
d     lanzhou
dtype: object

In [5]:
pd.Series(data=data)

0     beijing
1    shanghai
2     tianjin
3     lanzhou
dtype: object

In [10]:
cities={'beijing':1,'shanghai':2,'guangzhou':3,'shenzhen':4,'hangzhou':5}
ct=pd.Series(cities,name='cities')

In [15]:
# dataframe
data2={
    'state':['ohio','ohio','ohio','neveda','neveda'],
    'year':[2000,2001,2002,2001,2002],
    'pop':[1.5,1.7,3.6,2.4,2.9]
}

In [18]:
frame=pd.DataFrame(data=data2,columns=['year','state','pop'])

In [21]:
frame[frame['pop']>2.0]

year   state  pop
2  2002    ohio  3.6
3  2001  neveda  2.4
4  2002  neveda  2.9

In [24]:
frame.index=['one','two','three','four','five']
frame

year   state  pop
one    2000    ohio  1.5
two    2001    ohio  1.7
three  2002    ohio  3.6
four   2001  neveda  2.4
five   2002  neveda  2.9

In [29]:
# 显示一行
frame.loc['three']

year     2002
state    ohio
pop       3.6
Name: three, dtype: object

In [32]:
# 索引键必须为整数
frame.iloc[0]

year     2000
state    ohio
pop       1.5
Name: one, dtype: object

In [36]:
frame['debt']=np.arange(5)
frame

year   state  pop  debt
one    2000    ohio  1.5     0
two    2001    ohio  1.7     1
three  2002    ohio  3.6     2
four   2001  neveda  2.4     3
five   2002  neveda  2.9     4

In [38]:
val=pd.Series([0.6,0.35,0.72],index=['one','two','four'])
frame['discount']=val
frame

year   state  pop  debt  discount
one    2000    ohio  1.5     0      0.60
two    2001    ohio  1.7     1      0.35
three  2002    ohio  3.6     2       NaN
four   2001  neveda  2.4     3      0.72
five   2002  neveda  2.9     4       NaN

In [41]:
frame['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [43]:
# 转置
frame.T

one   two three    four    five
year      2000  2001  2002    2001    2002
state     ohio  ohio  ohio  neveda  neveda
pop        1.5   1.7   3.6     2.4     2.9
debt         0     1     2       3       4
discount   0.6  0.35   NaN    0.72     NaN

In [52]:
frame.reindex(index=['one','four','six'],fill_value=0)

year   state  pop  debt  discount
one   2000    ohio  1.5     0      0.60
four  2001  neveda  2.4     3      0.72
six      0       0  0.0     0      0.00

In [59]:
from pandas import DataFrame

df1=DataFrame(data=np.arange(12.).reshape((3,4)),columns=list('abcd'))
df2=DataFrame(data=np.arange(20.).reshape((4,5)),columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [61]:
# dataframe相加
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [63]:
# another
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [77]:
# third
df1=df1.reindex(columns=df2.columns,index=df2.index,fill_value=0)

In [78]:
df1+df2

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [82]:
a1=np.arange(12).reshape((3,4))
a2=np.array([1,2,3,4])
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a1-a2

array([[-1, -1, -1, -1],
       [ 3,  3,  3,  3],
       [ 7,  7,  7,  7]])

In [86]:
a1*a2

array([[ 0,  2,  6, 12],
       [ 4, 10, 18, 28],
       [ 8, 18, 30, 44]])

In [89]:
frame2=DataFrame(np.random.randn(3,4))
frame2

0         1         2         3
0 -2.397269 -0.107300  0.245089  0.449407
1 -0.228340 -0.893619  0.916350 -1.760879
2  0.110951  0.901471 -1.243634 -0.342373

In [92]:
frame2.abs()

0         1         2         3
0  2.397269  0.107300  0.245089  0.449407
1  0.228340  0.893619  0.916350  1.760879
2  0.110951  0.901471  1.243634  0.342373

In [95]:
# dataframe的函数应用和映射
f=lambda x: x.max()-x.min()
# apply方法，默认为轴0，即沿着列的方向
frame2.apply(f)

0    2.508220
1    1.795089
2    2.159984
3    2.210286
dtype: float64

In [97]:
# another
frame2.max()-frame2.min()

0    2.508220
1    1.795089
2    2.159984
3    2.210286
dtype: float64

In [101]:
# 格式化
# applymap元素级函数
f1=lambda x: "%.2f" % x
frame2.applymap(f1)

0      1      2      3
0  -2.40  -0.11   0.25   0.45
1  -0.23  -0.89   0.92  -1.76
2   0.11   0.90  -1.24  -0.34

In [104]:
# 也可以使用函数
def f(x):
    return pd.Series([x.max(),x.min()],index=['max','min'])

frame2.apply(f)

0         1         2         3
max  0.110951  0.901471  0.916350  0.449407
min -2.397269 -0.893619 -1.243634 -1.760879

In [106]:
# 对每个元素进行变化
frame2[3].map(lambda x: np.abs(x))

0    0.449407
1    1.760879
2    0.342373
Name: 3, dtype: float64

In [110]:
# 排序和排名
# sort_index可以按照轴axis对索引对索引所在的列进行排序，对列之间的值不排序
# e.g
frame2.sort_index(axis=1,ascending=True)

0         1         2         3
0 -2.397269 -0.107300  0.245089  0.449407
1 -0.228340 -0.893619  0.916350 -1.760879
2  0.110951  0.901471 -1.243634 -0.342373

In [116]:
# 根据一个或者多个列的值进行排序
df3=DataFrame({'a':[4,7,-3,2],'c':[0,2,1,3]})
df3

a  c
0  4  0
1  7  2
2 -3  1
3  2  3

In [118]:
# deprecated
# df3.sort_index(by='a')
df3.sort_values(by=['a','c'])

a  c
2 -3  1
3  2  3
0  4  0
1  7  2

In [120]:
# rank函数根据元数据中出现的顺序给出排名
df3.rank()

a    c
0  3.0  1.0
1  4.0  3.0
2  1.0  2.0
3  2.0  4.0

In [122]:
# 沿着行的方向
df3.rank(axis=1)

a    c
0  2.0  1.0
1  2.0  1.0
2  1.0  2.0
3  1.0  2.0

In [125]:
# 汇总和统计
df4=DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=list('abcd'),columns=['one','two'])
df4

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [128]:
# 默认的轴为0
df4.sum()

one    9.25
two   -5.80
dtype: float64

In [131]:
# skipna默认为true，即跳过nan进行统计
df4.mean(axis=1)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [133]:
# 求值最大的索引值，
# argmax：最大值索引的位置(整数值)
df4.idxmax()

one    b
two    d
dtype: object

In [134]:
# 累计和
df4.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [135]:
# 查看汇总统计信息
df4.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [140]:
# 计算丰度、偏度
# 偏度
frame2.skew()
# 丰度
# frame2.kurt()

0   -1.611701
1    0.368301
2   -1.041809
3   -0.810259
dtype: float64

In [155]:
import pandas_datareader.data as web

all_data={}
for ticker in ['AAPL','IBM','MSFT','GOOG']:
    all_data[ticker]=web.get_data_yahoo(ticker,'1/1/2000','1/1/2010')
    
price=DataFrame({tic:data['Adj Close'] for tic,data in all_data.items()})

volume=DataFrame({tic:data['Volume'] for tic,data in all_data.items()})

In [160]:
# 计算百分数变化
res=price.pct_change()
res.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2009-12-24  0.034339  0.004385  0.002587  0.011117
2009-12-28  0.012294  0.013326  0.005484  0.007098
2009-12-29 -0.011862 -0.003477  0.007058 -0.005571
2009-12-30  0.012148  0.005461 -0.013699  0.005376
2009-12-31 -0.004300 -0.012597 -0.015504 -0.004416

In [163]:
# 相关系数
res.MSFT.corr(res.IBM)

0.4943584064707691

In [166]:
# 协方差
res.MSFT.cov(res.IBM)

0.00021582152723415634

In [168]:
# 
res.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.412392  0.423598  0.470676
IBM   0.412392  1.000000  0.494358  0.390689
MSFT  0.423598  0.494358  1.000000  0.443586
GOOG  0.470676  0.390689  0.443586  1.000000

In [170]:
res.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.001030  0.000254  0.000309  0.000303
IBM   0.000254  0.000369  0.000216  0.000142
MSFT  0.000309  0.000216  0.000516  0.000205
GOOG  0.000303  0.000142  0.000205  0.000580

In [174]:
# 与其他series或者dataframe计算相关系数
res.corrwith(res.MSFT)

AAPL    0.423598
IBM     0.494358
MSFT    1.000000
GOOG    0.443586
dtype: float64

In [177]:
res.corrwith(volume)

AAPL   -0.057665
IBM    -0.006592
MSFT   -0.014228
GOOG    0.062647
dtype: float64

In [179]:
obj=pd.Series(list('abcdabcdddacb'))
obj

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     d
9     d
10    a
11    c
12    b
dtype: object

In [181]:
obj.unique()

array(['a', 'b', 'c', 'd'], dtype=object)

In [183]:
obj.value_counts()

d    4
c    3
b    3
a    3
dtype: int64

In [185]:
# isin函数，用于判断序列中的元素是不是在指定的范围之内，返回一个布尔值
mask=obj.isin(list('bcef'))
mask

0     False
1      True
2      True
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10    False
11     True
12     True
dtype: bool

In [188]:
# 返回子集
obj[mask]

1     b
2     c
5     b
6     c
11    c
12    b
dtype: object

In [191]:
# 异常值的处理
# 滤除异常 数据
data=DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,np.nan]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  NaN

In [199]:
# dropna方法默认丢弃 任何 还有缺失值的行
cleaned=data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [202]:
# how方式指定要丢弃的部分，how='all'表示只丢弃全为nan的行，在该方式下需要指定轴axis的方向
df5=data.dropna(how='all')
df5

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  NaN

In [204]:
# 填充丢失数据
df5.fillna(0)

0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
3  0.0  6.5  0.0

In [211]:
# df5.fillna(df5.min())
df5.fillna(method='pad')

0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
3  1.0  6.5  3.0

In [215]:
# 层次化索引
data=pd.Series(np.random.randn(10),
               index=[['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
data

a  1   -0.673755
   2   -2.799586
   3   -1.703452
b  1   -1.184776
   2    1.941510
   3    2.492873
c  1   -1.124643
   2    0.624810
d  2    0.801717
   3   -0.360018
dtype: float64

In [217]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [221]:
# 范围选取
data['b':'c']

b  1   -1.184776
   2    1.941510
   3    2.492873
c  1   -1.124643
   2    0.624810
dtype: float64

In [223]:
# 内层选取
data[:,2]

a   -2.799586
b    1.941510
c    0.624810
d    0.801717
dtype: float64

In [226]:
# 重排，unstack方法可将层次化索引编排为一个dataframe
unstack=data.unstack()
unstack

1         2         3
a -0.673755 -2.799586 -1.703452
b -1.184776  1.941510  2.492873
c -1.124643  0.624810       NaN
d       NaN  0.801717 -0.360018

In [228]:
# stack为unstack的逆运算
unstack.stack()

a  1   -0.673755
   2   -2.799586
   3   -1.703452
b  1   -1.184776
   2    1.941510
   3    2.492873
c  1   -1.124643
   2    0.624810
d  2    0.801717
   3   -0.360018
dtype: float64

In [231]:
df=DataFrame(np.arange(12).reshape((4,3)),
            index=[['a','a','b','b'],[1,2,1,2]],
            columns=[['ohio','ohio','colorado'],['green','red','green']])
df

ohio     colorado
    green red    green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [233]:
df.loc['a']

ohio     colorado
  green red    green
1     0   1        2
2     3   4        5

In [239]:
# 设置索引名 和 轴标签名
df.index.names=['key1','key2']
df.columns.names=['state','color']
df

state      ohio     colorado
color     green red    green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [241]:
df['ohio']

color      green  red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [243]:
# 分级顺序重排
df.swaplevel('key1','key2')

state      ohio     colorado
color     green red    green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [246]:
# 分级交换重排
t=df.swaplevel(0,1)

In [249]:
# level参数在multiIndex的序列中确定索引的位置
t.sort_index(level=0)

state      ohio     colorado
color     green red    green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [254]:
# !!! 
#  根据级别统计汇总
df.sum(level=1)# level=1 or level='key2'

state  ohio     colorado
color green red    green
key2                    
1         6   8       10
2        12  14       16

In [257]:
# another
# 考虑level 和 axis两方面
# axis=1 表示沿着行的方向
res1=df.sum(level='color',axis=1)
res1

color      green  red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [259]:
# level可以选取不同的方向
res1.sum(level=0)

color  green  red
key1             
a         10    5
b         34   17